version: 2

sphinx:
    configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - python -m pip install sphinx_rtd_theme
      - python -m pip install recommonmark

formats: []

python:
    install:
        - requirements: requirements.txt